# programming language
lang: cc

# output directory for storing html report
output: /Users/esmaeil/MyData/MyProjects/cse101/pa6

# repositories for base files
base_repos:
  - git@github.com:esmaeil-mirvakili/CSE101Examples.git

# files that need to be excluded
base_files:
  - '*.c'
  - '*.cpp'
  - '*.cc'

# gitlab group(s) of the course for current quarter
this_quarter_groups:
  - fall24

# gitlab group(s) of the course for previous quarters
previous_quarter_groups:
  - winter24
  - fall23
  - spring23
  - winter23
  - spring22
  - winter22
#  - spring21
#  - winter21

# branch name
assignment_branch: pa6

# project path
assignment_path: pa6/

# files to compare
assignment_files:
  - Arithmetic.cpp
  - BigInteger.cpp

# cooldown between moss requests
moss_request_cooldown: 120

# (optional) moss options
# remove this part to use default options
moss_options:
  m: 50     # ignore limit
  d: 0      # directory mode
  x: 0      # experimental server
  c: ""     # comment string
  n: 30    # number of matching files

